source C:/masters/masters_automation/generate_procs.tcl
start_gui
open_project D:/HDLGen-ChatGPT/User_Projects/LukeAND/LukeAND/VHDL/AMDprj/LukeAND.xpr
create_bd_file LukeAND_bd
add_processing_unit
set_property source_mgmt_mode All [current_project]
add_module LukeAND LukeAND_0
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1
add_axi_gpio_all_output AND2In1 1
connect_gpio_all_output_to_module_port AND2In1 LukeAND_0
add_axi_gpio_all_output AND2In0 1
connect_gpio_all_output_to_module_port AND2In0 LukeAND_0
add_axi_gpio_all_input ANDOut 1
connect_gpio_all_input_to_module_port ANDOut LukeAND_0
add_axi_interconnect 1 3
connect_bd_intf_net -boundary_type upper [get_bd_intf_pins axi_interconnect_0/M00_AXI] [get_bd_intf_pins AND2In1/S_AXI]
connect_bd_intf_net -boundary_type upper [get_bd_intf_pins axi_interconnect_0/M01_AXI] [get_bd_intf_pins AND2In0/S_AXI]
connect_bd_intf_net -boundary_type upper [get_bd_intf_pins axi_interconnect_0/M02_AXI] [get_bd_intf_pins ANDOut/S_AXI]
add_system_reset_ip
connect_bd_intf_net [get_bd_intf_pins processing_system7_0/M_AXI_GP0] -boundary_type upper [get_bd_intf_pins axi_interconnect_0/S00_AXI]
run_bd_automation_rule_processor
run_bd_automation_rule_interconnect
run_bd_automation_rule_io AND2In1/s_axi_aclk
run_bd_automation_rule_io AND2In0/s_axi_aclk
run_bd_automation_rule_io ANDOut/s_axi_aclk
run_bd_block_automation
run_addr_editor_auto_assign
validate_bd
create_hdl_wrapper D:/HDLGen-ChatGPT/User_Projects/LukeAND/LukeAND/VHDL/AMDprj/LukeAND.srcs/sources_1/bd LukeAND_bd
set_wrapper_top LukeAND_bd_wrapper
generate_bitstream
export_bd
wait_on_run
stop_gui
close_design
wait_on_run
exit