# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z1_c/physical_contr.xdc

# Block Designs: bd/cb4cled_design/cb4cled_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design || ORIG_REF_NAME==cb4cled_design} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_processing_system7_0_0/cb4cled_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_processing_system7_0_0 || ORIG_REF_NAME==cb4cled_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_CB4CLED_Top_0_0/cb4cled_design_CB4CLED_Top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_CB4CLED_Top_0_0 || ORIG_REF_NAME==cb4cled_design_CB4CLED_Top_0_0} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_axi_gpio_0_0/cb4cled_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_axi_gpio_0_0 || ORIG_REF_NAME==cb4cled_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_clk_0/cb4cled_design_clk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_clk_0 || ORIG_REF_NAME==cb4cled_design_clk_0} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_rst_0/cb4cled_design_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_rst_0 || ORIG_REF_NAME==cb4cled_design_rst_0} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_rst_1/cb4cled_design_rst_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_rst_1 || ORIG_REF_NAME==cb4cled_design_rst_1} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_rst_2/cb4cled_design_rst_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_rst_2 || ORIG_REF_NAME==cb4cled_design_rst_2} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_rst_3/cb4cled_design_rst_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_rst_3 || ORIG_REF_NAME==cb4cled_design_rst_3} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_clk_1/cb4cled_design_clk_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_clk_1 || ORIG_REF_NAME==cb4cled_design_clk_1} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_clk_2/cb4cled_design_clk_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_clk_2 || ORIG_REF_NAME==cb4cled_design_clk_2} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_TC_0/cb4cled_design_TC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_TC_0 || ORIG_REF_NAME==cb4cled_design_TC_0} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_proc_sys_reset_0_0/cb4cled_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_proc_sys_reset_0_0 || ORIG_REF_NAME==cb4cled_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_xbar_1/cb4cled_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_xbar_1 || ORIG_REF_NAME==cb4cled_design_xbar_1} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_ps7_0_axi_periph_0/cb4cled_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==cb4cled_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cb4cled_design/ip/cb4cled_design_auto_pc_1/cb4cled_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cb4cled_design_auto_pc_1 || ORIG_REF_NAME==cb4cled_design_auto_pc_1} -quiet] -quiet

# XDC: bd/cb4cled_design/cb4cled_design_ooc.xdc
