-- Title Section Start
-- Generated by HDLGen, Github https://github.com/fearghal1/HDLGen-ChatGPT, on 19-October-2023 at 15:01

-- Component Name : LukeAND
-- Title          : AND2_1_L

-- Author(s)      : LC
-- Organisation   : University of Galway
-- Email          : LC@G.COM
-- Date           : 19/10/2023

-- Description
-- The component is a simple 2 input 1 output AND gate. 
-- Created from scratch in HDLGen

-- entity signal dictionary
-- AND2In1	Bit 1 Input
-- AND2In0	Bit 0 Input
-- ANDOut	Single Output Bit

-- internal signal dictionary
-- None

-- Title Section End
-- library declarations
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.MainPackage.all;

-- entity declaration
entity LukeAND is 
Port(
	AND2In1 : in std_logic;
	AND2In0 : in std_logic;
	ANDOut : out std_logic
);
end entity LukeAND;

architecture Combinational of LukeAND is
-- Internal signal declarations
-- None

begin

--- ANDOut_c: ANDOut <= AND2In1 and AND2In0;


end Combinational;