# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado/cb4cled-jn-application_cleaned/CB4CLED/vhdl/xilinxprj/CB4CLED_Top.cache/wt [current_project]
set_property parent.project_path D:/Vivado/cb4cled-jn-application_cleaned/CB4CLED/vhdl/xilinxprj/CB4CLED_Top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo d:/Vivado/cb4cled-jn-application_cleaned/CB4CLED/vhdl/xilinxprj/CB4CLED_Top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Vivado/cb4cled-jn-application_cleaned/CB4CLED/vhdl/HDLmodel/CB4CLED.vhd
  D:/Vivado/cb4cled-jn-application_cleaned/CB4CLED/vhdl/HDLmodel/singleShot.vhd
  D:/Vivado/cb4cled-jn-application_cleaned/CB4CLED/vhdl/HDLmodel/CB4CLED_Top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado/cb4cled-jn-application_cleaned/CB4CLED/vhdl/xilinxprj/CB4CLED_Top.srcs/constrs_1/imports/pynq-z2_v1.0.xdc/physical_constr.xdc
set_property used_in_implementation false [get_files D:/Vivado/cb4cled-jn-application_cleaned/CB4CLED/vhdl/xilinxprj/CB4CLED_Top.srcs/constrs_1/imports/pynq-z2_v1.0.xdc/physical_constr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CB4CLED_Top -part xc7z020clg400-1 -no_iobuf


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CB4CLED_Top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file CB4CLED_Top_utilization_synth.rpt -pb CB4CLED_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
