@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Sep 22 15:08:21 +0100 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim CB4CLED_Top_TB_behav -key {Behavioral:sim_1:Functional:CB4CLED_Top_TB} -tclbatch CB4CLED_Top_TB.tcl -protoinst "protoinst_files/cb4cled_design.protoinst" -view C:/Users/canny/Documents/5th Year ECE/Project/PYNQ/Tutorials/cb4cled/cb4cled-jn-application/CB4CLED/vhdl/xilinxprj/simulation/CB4CLED_TB_behav.wcfg -view C:/Users/canny/Documents/5th Year ECE/Project/PYNQ/Tutorials/cb4cled/cb4cled-jn-application/CB4CLED/vhdl/xilinxprj/simulation/CB4CLED_Top_TB_behav.wcfg -log simulate.log"
call xsim  CB4CLED_Top_TB_behav -key {Behavioral:sim_1:Functional:CB4CLED_Top_TB} -tclbatch CB4CLED_Top_TB.tcl -protoinst "protoinst_files/cb4cled_design.protoinst" -view C:/Users/canny/Documents/5th Year ECE/Project/PYNQ/Tutorials/cb4cled/cb4cled-jn-application/CB4CLED/vhdl/xilinxprj/simulation/CB4CLED_TB_behav.wcfg -view C:/Users/canny/Documents/5th Year ECE/Project/PYNQ/Tutorials/cb4cled/cb4cled-jn-application/CB4CLED/vhdl/xilinxprj/simulation/CB4CLED_Top_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
