name: Build 
on:
  workflow_dispatch:
  
permissions:
  contents: write
  issues: write

jobs:
  build_executable:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application with PyInstaller
        run: |
          pyinstaller main.spec

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: PYNQ-SoC-Builder
          path: dist/PYNQ-SoC-Builder.exe
